import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Belajar Next Js',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const menuItem = (url: string, title: string) => (
    <li className="">
      <Link href={url}>{title}</Link>
    </li>
  );
  return (
    <html lang="en">
      <body className={`container mx-auto py-[10px] ${inter.className}`}>
        <ul className="rounded inline-flex space-x-4 bg-stone-800 p-3 text-white font-medium mb-5">
          {menuItem('/', 'Home')}
          {menuItem('/dashboard', 'Dashboard')}
          {menuItem('/calculator', 'Calculator')}
          {menuItem('/cari', 'Cari Orang')}
        </ul>
        {children}
      </body>
    </html>
  );
}
